# Generated by Django 2.0 on 2020-07-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shoppinglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
