# Generated by Django 2.0 on 2020-07-25 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='item',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registration.user'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registration.shopkeeper'),
        ),
    ]
