# Generated by Django 2.0 on 2020-07-25 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200726_0248'),
        ('customer', '0002_auto_20200726_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeforcust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.TimeField()),
                ('people_count', models.IntegerField()),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registration.user')),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registration.shopkeeper')),
            ],
        ),
    ]
