# Generated by Django 2.0 on 2020-07-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_timeforcust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
