# Generated by Django 2.0 on 2020-07-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200726_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='date',
            field=models.TimeField(blank=True),
        ),
    ]
